image: alpine

stages:
  - sync

sync:
  only:
    - master
    - develop
    - release
    - unstable
    - testing

  stage: sync
  script:
    - apk update
    - apk add git openssh-client

    - eval $(ssh-agent -s)
    - echo $(which ssh-add)
    - TMPFILE=$(mktemp) && chmod 0600 $TMPFILE && echo "$GITHUB_DEPLOY_KEY" >$TMPFILE && ssh-add $TMPFILE && rm $TMPFILE
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

    - git remote get-url github || git remote add github git@github.com:kaplan2539/synctest
    - git push github HEAD:$CI_BUILD_REF_NAME
